-- V1__create_clientes.sql

create table if not exists clientes (
  id            bigint generated by default as identity primary key,
  nome          varchar(255) not null,
  nuit          varchar(50) unique,
  bi            varchar(50) unique,
  endereco      varchar(255),
  telefone      varchar(50),
  email         varchar(255),
  tipo_cliente  varchar(30),
  renda_mensal  numeric(14,2),
  status        varchar(20) not null,
  created_at    timestamp with time zone not null default now(),
  updated_at    timestamp with time zone not null default now()
);

-- começa a sequência a partir de 100
alter table clientes alter column id restart with 100;

-- índices úteis
create index if not exists idx_clientes_nome   on clientes (nome);
create index if not exists idx_clientes_status on clientes (status);
