create table if not exists utilizadores (
  id bigint generated by default as identity primary key,
  username varchar(120) not null unique,
  name varchar(150) not null,
  password_hash varchar(255) not null,
  role varchar(40) not null,
  activo boolean not null default true,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_utilizadores_role on utilizadores(role);
create index if not exists idx_utilizadores_activo on utilizadores(activo);
